version: "3.8"
services:
  mongodb:
    container_name: mongo
    image: mongo:latest
    volumes:
      - fakeapivolume:/data/db
    ports:
      - "27017:27017"

  backend:
    container_name: backend
    image: saimon4u/fakeapi-backend:latest
    environment:
      MONGO_URI: ${MONGO_URI}
      PORT: ${PORT}
      JWT_SECRET: ${JWT_SECRET}
      SALT: ${SALT}
    ports:
      - "3000:3000"
    depends_on:
      - mongodb

  frontend:
    container_name: frontend
    image: saimon4u/fakeapi-frontend:latest
    environment:
      VITE_BACKEND_HOST: ${VITE_BACKEND_HOST}
    ports:
      - "5173:5173"

volumes:
  fakeapivolume: