version: "3.8"
services:
  mongodb:
    container_name: mongo
    image: mongo:latest
    volumes:
      - fakeapivolume:/data/db
    ports:
      - "27017:27017"

  backend:
    container_name: backend
    build: ./backend
    environment:
      PORT: 3000
      JWT_SECRET: "secret"
      MONGO_URI: "mongodb://mongo:27017/fakeapidb"
      SALT: "10"
    ports:
      - "3000:3000"
    depends_on:
      - mongodb

  frontend:
    container_name: frontend
    build: ./frontend
    environment:
      VITE_BACKEND_HOST: "http://localhost:3000/api/"
    ports:
      - "5173:5173"
    depends_on:
      - backend

  nginx:
    container_name: nginx
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - frontend
      - backend

volumes:
  fakeapivolume:
