version: "3.8"
services:
  mongodb:
    container_name: mongo
    image: mongo:latest
    volumes:
      - fakeapivolume:/data/db
    ports:
      - "27017:27017"

  backend:
    container_name: backend
    image: saimon4u/fakeapi-backend:latest
    env_file:
      - ./backend/.env
    ports:
      - "3000:3000"
    depends_on:
      - mongodb

  frontend:
    container_name: frontend
    image: saimon4u/fakeapi-frontend:latest
    env_file:
      - ./frontend/.env
    ports:
      - "80:5173"

volumes:
  fakeapivolume:
    external: true
