apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: saimon4u/fakeapi-backend:latest
          ports:
            - containerPort: 3000
          env:
            - name: MONGO_URI
              valueFrom:
                secretKeyRef:
                  name: fakeapi-secrets
                  key: MONGO_URI
            - name: PORT
              valueFrom:
                secretKeyRef:
                  name: fakeapi-secrets
                  key: PORT
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: fakeapi-secrets
                  key: JWT_SECRET
            - name: SALT
              valueFrom:
                secretKeyRef:
                  name: fakeapi-secrets
                  key: SALT