apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-dep
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: saimon4u/fakeapi-monitor-backend:latest
        ports:
        - containerPort: 3000
        env:
        - name: MONGO_URI
          value: "mongodb://mongo-svc:27017/fakeapidb"
        - name: JWT_SECRET
          value: "secret"
        - name: SALT
          value: "10"
        - name: PORT
          value: "3000"
