apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: saimon4u/fakeapi-frontend:latest
          ports:
            - containerPort: 5173
          env:
            - name: VITE_BACKEND_HOST
              valueFrom:
                secretKeyRef:
                  name: fakeapi-secrets
                  key: VITE_BACKEND_HOST