apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-cmap
data:
  prometheus.yml: |
    global:
      scrape_interval: 5s
    scrape_configs:
      - job_name: 'backend'
        static_configs:
          - targets: ['backend-svc:3000']
      - job_name: 'kubernetes-pods'
        kubernetes_sd_configs:
        - role: pod
        relabel_configs:
          - source_labels: [__meta_kubernetes_pod_annotation_prometheus_io_scrape]
            action: keep
            regex: true